import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Providers } from './providers'
import './gloabals.css'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-inter',
  display: 'swap',
})

const SITE_URL = 'https://brandlift.dev'
const SITE_TITLE = 'BrandLift — Turn Raw Footage Into Polished Content in Minutes'
const SITE_DESCRIPTION =
  'AI-powered video editing for small businesses. Upload your raw iPhone clips and get back polished, platform-ready content for TikTok, Instagram, and YouTube — in minutes. Free during beta.'

export const metadata: Metadata = {
  title: {
    default: SITE_TITLE,
    template: '%s — BrandLift',
  },
  description: SITE_DESCRIPTION,
  keywords: [
    'AI video editing',
    'video editing for small business',
    'TikTok video editor',
    'Instagram Reels editor',
    'turn iPhone footage into social content',
  ],
  icons: {
    icon: '/brandlift-favicon.png',
    apple: '/brandlift-favicon.png',
  },
  authors: [{ name: 'BrandLift' }],
  creator: 'BrandLift',
  metadataBase: new URL(SITE_URL),
  // og:image / twitter:image are generated by app/opengraph-image.tsx + app/twitter-image.tsx
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: 'BrandLift',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
  },
}

export const viewport: Viewport = {
  themeColor: '#0D1117',
  colorScheme: 'dark',
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans antialiased bg-brand-bg text-brand-text min-h-screen">
        <Providers>
          {children}
        </Providers>
        <div id="toast-root" aria-live="polite" aria-atomic="false" className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 pointer-events-none" />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
